[package]
name = "nem"
version = "0.1.0"
authors = ["kyle-verhoog <kyle@verhoog.ca>"]
edition = "2018"

[dependencies]
toml = "^0.4"
serde = { version = "^1.0", features = ["derive"]}

[dev-dependencies]
walkdir = "2"

[[bin]]
name = "n"
path = "nem.rs"

[[test]]
name = "tests"
path = "tests.rs"
